baseURL = "https://dakes.github.io/science-communication-btc/"
languageCode = "en-us"
title = "Science Communication: BTC"
theme = "dream"
defaultContentLanguage = "en"
enableRobotsTXT = false

[params]
    background = "#fff"
    backgroundImage = "/science-communication-btc/blockchain-bright.svg"
    # Source: https://pixabay.com/vectors/blockchain-cryptocurrency-network-3277335/
    linkColor = "seagreen"

    # dark mode
    # defaultDark = true
    # backgroundDark = "#333"
    backgroundImageDark = "/science-communication-btc/blockchain-dark.svg"
    # Source: https://pixabay.com/vectors/blockchain-cryptocurrency-network-3277336/

    darkLinkColor = "darkseagreen"
    # darkNav = true
    # dark404 = true

    headerTitle = "Science Communication: BTC"

    [params.advanced]
        # from https://github.com/g1eny0ung/blog/blob/master/static/css/custom.css
        customCSS = ["css/custom.css"]
        # customJSBefore = []
        # customJS = []
