baseURL = "http://example.org/"
languageCode = "en-us"
title = "Science Communication: BTC"
theme = "dream"
defaultContentLanguage = "en"
enableRobotsTXT = false

[params]
    headerTitle = "Science Communication: BTC"

    [params.advanced]
        # from https://github.com/g1eny0ung/blog/blob/master/static/css/custom.css
        customCSS = ["css/custom.css"]
        # customJSBefore = []
        # customJS = []
