baseURL = "https://dakes.github.io/science-communication-btc/"
languageCode = "en-us"
title = "Science Communication: BTC"
theme = "dream"
defaultContentLanguage = "en"
enableRobotsTXT = false

[params]
    background = "#fff"
    # backgroundImage = "/me/background.jpg"
    linkColor = "seagreen"

    # dark mode
    # defaultDark = true
    backgroundDark = "#333"
    # backgroundImageDark = "/me/background.jpg"
    darkLinkColor = "darkseagreen"
    # darkNav = true
    # dark404 = true

    headerTitle = "Science Communication: BTC"

    [params.advanced]
        # from https://github.com/g1eny0ung/blog/blob/master/static/css/custom.css
        customCSS = ["css/custom.css"]
        # customJSBefore = []
        # customJS = []
